name: Build and Push Image to Quay.io

on:
  push:
    branches: [ main ] # Or whichever branch you want to build from

jobs:
  build:
    name: Build, Attest, and Push Image
    runs-on: ubuntu-22.04

    # Permissions needed for SLSA attestation
    permissions:
      contents: read
      id-token: write   # Required to sign the SLSA attestation
      packages: write   # Required to push the attestation to Quay.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: mbicak/test-container
          tags: latest ${{ steps.sha.outputs.sha }}
          containerfiles: |
            ./src/main/docker/Dockerfile.jvm
          attestation-type: slsaprovenance

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"