name: Build and Push Image to Quay.io

on:
  push:
    branches: [ main ] # Or whichever branch you want to build from

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    outputs:
      image: "quay.io/mbicak/test-container"
      digest: ${{ steps.build-image.outputs.image-digest }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: mbicak/test-container
          tags: latest ${{ steps.sha.outputs.sha }}
          containerfiles: |
            ./src/main/docker/Dockerfile.jvm

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io # This combines with the base name above
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  # JOB 2: Generate and push the SLSA provenance
  provenance:
    name: Generate Provenance
    needs: [build] # This job runs *after* the build job
    runs-on: ubuntu-latest

    # Permissions for this job: get OIDC token, write attestations
    permissions:
      actions: read
      id-token: write # Required for signing
      packages: write # Required to push attestation

    steps:
      - name: Generate SLSA Provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
        with:
          # Get the full image name from the build job's output
          image: ${{ needs.build.outputs.image }}
          # Get the exact digest from the build job's output
          digest: ${{ needs.build.outputs.digest }}

          # Authenticate to Quay.io
          registry-username: ${{ secrets.QUAY_USER }}
        secrets:
          registry-password: ${{ secrets.QUAY_PASSWORD }}